"""Phase 04 persistence and reproducibility schema.

Revision ID: 0002_phase04
Revises: 0001_phase02
"""
from __future__ import annotations

from typing import Sequence

from alembic import op

revision: str = "0002_phase04"
down_revision: str | None = "0001_phase02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

DDL = [
    "CREATE EXTENSION IF NOT EXISTS vector",
    """CREATE TABLE dataset_versions (version varchar(160) PRIMARY KEY, schema_version varchar(80) NOT NULL, label_taxonomy_version varchar(80) NOT NULL, manifest_checksum varchar(64) NOT NULL UNIQUE, content_checksum varchar(64) NOT NULL UNIQUE, split_seed bigint NOT NULL, record_count integer NOT NULL CHECK (record_count >= 0), family_count integer NOT NULL CHECK (family_count >= 0), research_ready boolean NOT NULL, manifest_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now())""",
    """CREATE TABLE incident_families (dataset_version varchar(160) NOT NULL REFERENCES dataset_versions(version) ON DELETE RESTRICT, family_id varchar(120) NOT NULL, split varchar(16) NOT NULL CHECK (split IN ('train','validation','test')), source_family_key varchar(320) NOT NULL, root_cause_codes jsonb NOT NULL, family_metadata jsonb NOT NULL DEFAULT '{}'::jsonb, PRIMARY KEY (dataset_version,family_id), UNIQUE (dataset_version,source_family_key), UNIQUE (dataset_version,family_id,split))""",
    """CREATE TABLE incidents (dataset_version varchar(160) NOT NULL, incident_id varchar(120) NOT NULL, family_id varchar(120) NOT NULL, split varchar(16) NOT NULL CHECK (split IN ('train','validation','test')), title text NOT NULL, description text NOT NULL, root_cause_code varchar(120) NOT NULL, root_cause_category varchar(120) NOT NULL, source_checksum varchar(64) NOT NULL, source_record_id varchar(320) NOT NULL, is_synthetic boolean NOT NULL, incident_metadata jsonb NOT NULL DEFAULT '{}'::jsonb, PRIMARY KEY (dataset_version,incident_id), UNIQUE (dataset_version,source_record_id), FOREIGN KEY (dataset_version,family_id,split) REFERENCES incident_families(dataset_version,family_id,split) ON DELETE RESTRICT)""",
    """CREATE TABLE model_versions (model_version_id varchar(160) PRIMARY KEY, model_id varchar(320) NOT NULL, revision varchar(160) NOT NULL, license varchar(120), metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, UNIQUE (model_id,revision))""",
    """CREATE TABLE adapter_versions (adapter_version_id varchar(160) PRIMARY KEY, model_version_id varchar(160) NOT NULL REFERENCES model_versions(model_version_id), adapter_id varchar(320) NOT NULL, revision varchar(160) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, UNIQUE (adapter_id,revision), UNIQUE (adapter_version_id,model_version_id))""",
    """CREATE TABLE knowledge_base_versions (kb_version varchar(160) PRIMARY KEY, embedding_model_id varchar(320) NOT NULL, embedding_model_revision varchar(160) NOT NULL, chunker_version varchar(160) NOT NULL, chunk_size integer NOT NULL CHECK (chunk_size > 0), overlap integer NOT NULL CHECK (overlap >= 0 AND overlap < chunk_size), reranker_id varchar(320), reranker_revision varchar(160), manifest_checksum varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb)""",
    """CREATE TABLE kb_documents (kb_version varchar(160) NOT NULL REFERENCES knowledge_base_versions(kb_version), document_id varchar(160) NOT NULL, source_uri text NOT NULL, source_checksum varchar(64) NOT NULL, title text, document_metadata jsonb NOT NULL DEFAULT '{}'::jsonb, PRIMARY KEY (kb_version,document_id))""",
    """CREATE TABLE kb_chunks (kb_version varchar(160) NOT NULL, chunk_id varchar(160) NOT NULL, document_id varchar(160) NOT NULL, chunk_index integer NOT NULL CHECK (chunk_index >= 0), text text NOT NULL, embedding vector(1536), source_family_id varchar(120), chunk_metadata jsonb NOT NULL DEFAULT '{}'::jsonb, PRIMARY KEY (kb_version,chunk_id), UNIQUE (kb_version,document_id,chunk_index), FOREIGN KEY (kb_version,document_id) REFERENCES kb_documents(kb_version,document_id))""",
    """CREATE TABLE experiments (experiment_id varchar(160) PRIMARY KEY, study_id varchar(160) NOT NULL, pipeline_type varchar(24) NOT NULL CHECK (pipeline_type IN ('ZERO_SHOT','RAG','FINETUNED','COMBINED')), dataset_version varchar(160) NOT NULL REFERENCES dataset_versions(version), test_split_manifest_checksum varchar(64) NOT NULL, label_taxonomy_version varchar(80) NOT NULL, model_version_id varchar(160) NOT NULL REFERENCES model_versions(model_version_id), adapter_version_id varchar(160), kb_version varchar(160) REFERENCES knowledge_base_versions(kb_version), embedding_model_revision varchar(160), chunker_version varchar(160), chunk_size integer, overlap integer, top_k integer, reranker_id varchar(320), reranker_revision varchar(160), prompt_version varchar(160) NOT NULL, output_schema_version varchar(160) NOT NULL, generation_config jsonb NOT NULL, temperature double precision NOT NULL CHECK (temperature >= 0), confidence_method varchar(160) NOT NULL, calibration_version varchar(160), seed bigint NOT NULL, evaluator_version varchar(160) NOT NULL, ragas_or_judge_versions jsonb, git_commit varchar(64) NOT NULL, dependency_lock_checksum varchar(64) NOT NULL, hardware_runtime_descriptor text NOT NULL, cost_rate_snapshot_version varchar(160) NOT NULL, status varchar(24) NOT NULL CHECK (status IN ('planned','queued','running','completed','failed','cancelled')), config_json jsonb NOT NULL, config_hash varchar(64) NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, UNIQUE (experiment_id,dataset_version), UNIQUE (experiment_id,kb_version), FOREIGN KEY (adapter_version_id,model_version_id) REFERENCES adapter_versions(adapter_version_id,model_version_id), CHECK ((pipeline_type IN ('FINETUNED','COMBINED') AND adapter_version_id IS NOT NULL) OR (pipeline_type IN ('ZERO_SHOT','RAG') AND adapter_version_id IS NULL)), CHECK ((pipeline_type IN ('RAG','COMBINED') AND kb_version IS NOT NULL AND embedding_model_revision IS NOT NULL AND chunker_version IS NOT NULL AND chunk_size > 0 AND overlap >= 0 AND overlap < chunk_size AND top_k > 0) OR (pipeline_type IN ('ZERO_SHOT','FINETUNED') AND kb_version IS NULL AND embedding_model_revision IS NULL AND chunker_version IS NULL AND chunk_size IS NULL AND overlap IS NULL AND top_k IS NULL AND reranker_id IS NULL AND reranker_revision IS NULL)))""",
    """CREATE TABLE runs (run_id varchar(160) PRIMARY KEY, experiment_id varchar(160) NOT NULL REFERENCES experiments(experiment_id) ON DELETE CASCADE, attempt integer NOT NULL CHECK (attempt >= 1), status varchar(24) NOT NULL, started_at timestamptz, completed_at timestamptz, runtime_metadata jsonb NOT NULL DEFAULT '{}'::jsonb, UNIQUE (run_id,experiment_id), UNIQUE (experiment_id,attempt))""",
    """CREATE TABLE predictions (prediction_id varchar(160) PRIMARY KEY, run_id varchar(160) NOT NULL, experiment_id varchar(160) NOT NULL, dataset_version varchar(160) NOT NULL, incident_id varchar(120) NOT NULL, kb_version varchar(160), predicted_root_cause_code varchar(120) NOT NULL, confidence double precision CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)), output_json jsonb NOT NULL, latency_ms double precision, UNIQUE (run_id,incident_id), UNIQUE (prediction_id,kb_version), FOREIGN KEY (run_id,experiment_id) REFERENCES runs(run_id,experiment_id) ON DELETE CASCADE, FOREIGN KEY (experiment_id,dataset_version) REFERENCES experiments(experiment_id,dataset_version) ON DELETE CASCADE, FOREIGN KEY (experiment_id,kb_version) REFERENCES experiments(experiment_id,kb_version), FOREIGN KEY (dataset_version,incident_id) REFERENCES incidents(dataset_version,incident_id))""",
    """CREATE TABLE retrieval_traces (retrieval_trace_id varchar(160) PRIMARY KEY, prediction_id varchar(160) NOT NULL, kb_version varchar(160) NOT NULL, chunk_id varchar(160) NOT NULL, rank integer NOT NULL CHECK (rank >= 1), score double precision, trace_metadata jsonb NOT NULL DEFAULT '{}'::jsonb, UNIQUE (prediction_id,rank), FOREIGN KEY (prediction_id,kb_version) REFERENCES predictions(prediction_id,kb_version) ON DELETE CASCADE, FOREIGN KEY (kb_version,chunk_id) REFERENCES kb_chunks(kb_version,chunk_id))""",
    """CREATE TABLE metrics (metric_id varchar(160) PRIMARY KEY, experiment_id varchar(160) NOT NULL REFERENCES experiments(experiment_id) ON DELETE CASCADE, run_id varchar(160) REFERENCES runs(run_id) ON DELETE CASCADE, name varchar(160) NOT NULL, split varchar(16) CHECK (split IS NULL OR split IN ('train','validation','test')), value double precision NOT NULL, metric_metadata jsonb NOT NULL DEFAULT '{}'::jsonb)""",
    """CREATE TABLE failure_annotations (failure_annotation_id varchar(160) PRIMARY KEY, prediction_id varchar(160) NOT NULL REFERENCES predictions(prediction_id) ON DELETE CASCADE, taxonomy_version varchar(80) NOT NULL, failure_code varchar(160) NOT NULL, notes text, annotation_metadata jsonb NOT NULL DEFAULT '{}'::jsonb)""",
    """CREATE TABLE artifacts (artifact_id varchar(160) PRIMARY KEY, experiment_id varchar(160) NOT NULL REFERENCES experiments(experiment_id) ON DELETE CASCADE, kind varchar(120) NOT NULL, uri text NOT NULL, sha256 varchar(64) NOT NULL, size_bytes bigint CHECK (size_bytes IS NULL OR size_bytes >= 0), artifact_metadata jsonb NOT NULL DEFAULT '{}'::jsonb)""",
    """CREATE TABLE jobs (job_id varchar(160) PRIMARY KEY, experiment_id varchar(160) REFERENCES experiments(experiment_id) ON DELETE SET NULL, kind varchar(120) NOT NULL, idempotency_key varchar(200) NOT NULL UNIQUE, payload_hash varchar(64) NOT NULL, payload_json jsonb NOT NULL, status varchar(24) NOT NULL CHECK (status IN ('queued','running','completed','failed','cancelled')), attempt integer NOT NULL CHECK (attempt >= 1), result_json jsonb, error text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())""",
    """CREATE TABLE cost_records (cost_record_id varchar(160) PRIMARY KEY, experiment_id varchar(160) NOT NULL REFERENCES experiments(experiment_id) ON DELETE CASCADE, run_id varchar(160) REFERENCES runs(run_id) ON DELETE CASCADE, prediction_id varchar(160) REFERENCES predictions(prediction_id) ON DELETE CASCADE, cost_rate_snapshot_version varchar(160) NOT NULL, units_json jsonb NOT NULL, amount_usd numeric(18,8) NOT NULL CHECK (amount_usd >= 0))""",
    """CREATE FUNCTION evalforge_reject_version_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'historical version rows are immutable'; END $$""",
    "CREATE TRIGGER dataset_versions_immutable BEFORE UPDATE OR DELETE ON dataset_versions FOR EACH ROW EXECUTE FUNCTION evalforge_reject_version_mutation()",
    "CREATE TRIGGER model_versions_immutable BEFORE UPDATE OR DELETE ON model_versions FOR EACH ROW EXECUTE FUNCTION evalforge_reject_version_mutation()",
    "CREATE TRIGGER adapter_versions_immutable BEFORE UPDATE OR DELETE ON adapter_versions FOR EACH ROW EXECUTE FUNCTION evalforge_reject_version_mutation()",
    "CREATE TRIGGER knowledge_base_versions_immutable BEFORE UPDATE OR DELETE ON knowledge_base_versions FOR EACH ROW EXECUTE FUNCTION evalforge_reject_version_mutation()",
    """CREATE FUNCTION evalforge_freeze_completed_experiment() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.status = 'completed' AND NEW IS DISTINCT FROM OLD THEN RAISE EXCEPTION 'completed experiment rows are immutable'; END IF; RETURN NEW; END $$""",
    "CREATE TRIGGER experiments_freeze_completed BEFORE UPDATE ON experiments FOR EACH ROW EXECUTE FUNCTION evalforge_freeze_completed_experiment()",
]


def upgrade() -> None:
    for statement in DDL:
        op.execute(statement)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS cost_records, jobs, artifacts, failure_annotations, metrics, retrieval_traces, predictions, runs, experiments, kb_chunks, kb_documents, knowledge_base_versions, adapter_versions, model_versions, incidents, incident_families, dataset_versions CASCADE")
    op.execute("DROP FUNCTION IF EXISTS evalforge_freeze_completed_experiment()")
    op.execute("DROP FUNCTION IF EXISTS evalforge_reject_version_mutation()")
